application: jan-ken-pony
version: 0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(ico))
  static_files: static/ico/\1
  upload: static/ico/(.*\.(ico))

- url: /(.*\.(css))
  static_files: static/css/\1
  upload: static/css/(.*\.(css))


- url: /(.*\.(js))
  static_files: static/js/\1
  upload: static/js/(.*\.(js))

- url: /(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))

- url: /.*
  script: main.app



libraries:
- name: jinja2
  version: latest
